/* Bad Apple, 10s clip @ 15fps, 64x64 source frames upscaled 2x horizontally
 * to fill the real 128x64 panel (each source column drawn twice). Same
 * OLED wiring/init as oled_demo.c - see docs/fpga_gpio.md. Frame data
 * generated by scripts/video_to_frames.py, do not hand-edit that file.
 *
 * Build: scripts/c_compiler.sh examples/bad_apple.c bad_apple 0x400
 * Load:  scripts/load.sh build/bad_apple.bin
 */

#include "bad_apple_frames.c"

#define GPIO_BASE   0x10000000u
#define GPIO_DIR_LO (*(volatile unsigned int *)(GPIO_BASE + 0x00))
#define GPIO_OUT_LO (*(volatile unsigned int *)(GPIO_BASE + 0x08))

#define LED_BITS  0x3Fu      /* idx0-5 */
#define DC_BIT    (1u << 8)  /* idx8 */
#define RES_BIT   (1u << 9)  /* idx9 */
#define SCK_BIT   (1u << 11) /* idx11 */
#define MOSI_BIT  (1u << 12) /* idx12 */

/* Not calibrated like the UART bit timing in bootloader.c - just a rough
 * guess for ~1/15s. Raise/lower after watching it play once. */
#define FRAME_DELAY_ITERS 180000u

static unsigned int out_shadow = 0;

static void gpio_set(unsigned int bit, int level) {
    if (level) out_shadow |= bit; else out_shadow &= ~bit;
    GPIO_OUT_LO = out_shadow;
}

static void delay(unsigned int iters) {
    volatile unsigned int i = iters;
    while (i != 0) i--;
}

static void spi_write(unsigned char byte) {
    for (int i = 7; i >= 0; i--) {
        gpio_set(MOSI_BIT, byte & (1u << i));
        gpio_set(SCK_BIT, 1); /* SSD1306 samples MOSI on the rising edge */
        gpio_set(SCK_BIT, 0);
    }
}

static void oled_cmd(unsigned char byte) {
    gpio_set(DC_BIT, 0);
    spi_write(byte);
}

static void oled_data(unsigned char byte) {
    gpio_set(DC_BIT, 1);
    spi_write(byte);
}

static void oled_init(void) {
    gpio_set(RES_BIT, 0);
    delay(10000);
    gpio_set(RES_BIT, 1);
    delay(10000);

    /* same init sequence as oled_demo.c - see that file for what each
     * command means */
    static const unsigned char init_cmds[] = {
        0xAE,
        0xD5, 0x80,
        0xA8, 0x3F,
        0xD3, 0x00,
        0x40,
        0x8D, 0x14,
        0xA1,
        0xC8,
        0xDA, 0x12,
        0x81, 0xCF,
        0xD9, 0xF1,
        0xDB, 0x40,
        0xA4,
        0xA6,
        0xAF,
    };
    for (unsigned int i = 0; i < sizeof(init_cmds); i++) {
        oled_cmd(init_cmds[i]);
    }
}

static void play_frame(const unsigned char *src) {
    for (unsigned int page = 0; page < 8; page++) {
        oled_cmd((unsigned char)(0xB0 | page));
        oled_cmd(0x00);
        oled_cmd(0x10);

        for (unsigned int x = 0; x < BAD_APPLE_WIDTH; x++) {
            unsigned char b = src[page * BAD_APPLE_WIDTH + x];
            
            oled_data(b);
            oled_data(b);
        }
    }
}

__attribute__((section(".text.entry")))
void main(void) {
    GPIO_DIR_LO = LED_BITS | DC_BIT | RES_BIT | SCK_BIT | MOSI_BIT;

    oled_init();

    for (;;) {
        for (unsigned int f = 0; f < BAD_APPLE_COUNT; f++) {
            play_frame(bad_apple[f]);
            delay(FRAME_DELAY_ITERS);
        }
    }
}
