#!/usr/bin/env python3
"""Converts a video clip into a C array of SSD1306-format frames.

Each frame is WIDTHxHEIGHT, 1 bit/pixel, page-addressed the same way
examples/oled_demo.c's framebuf is: ceil(HEIGHT/8) pages of WIDTH bytes,
bit0 of each byte = the top row of that page (matches set_pixel()'s
layout, just at whatever WIDTH/HEIGHT you pick - a playback program using
WIDTH < 128 has to upscale itself when flushing to the real 128-wide panel).

Usage:
  scripts/video_to_frames.py <video_file> <output_c_file> \
      [--start SEC] [--duration SEC] [--fps N] \
      [--width N] [--height N] [--max-frames N] [--threshold N]

Requires ffmpeg (for decoding/scaling/trimming) and Pillow is NOT needed -
this reads ffmpeg's raw grayscale output directly.
"""
import argparse
import subprocess
import sys
from pathlib import Path


def extract_gray_frames(video_path: str, fps: int, width: int, height: int,
                         start: float, duration: float):
    """Yields raw width*height grayscale bytes per frame via an ffmpeg pipe."""
    cmd = ["ffmpeg"]
    if start > 0:
        cmd += ["-ss", str(start)]
    cmd += ["-i", video_path]
    if duration is not None:
        cmd += ["-t", str(duration)]
    cmd += [
        "-vf", f"fps={fps},scale={width}:{height}",
        "-pix_fmt", "gray",
        "-f", "rawvideo", "-",
    ]
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    frame_size = width * height
    while True:
        buf = proc.stdout.read(frame_size)
        if len(buf) < frame_size:
            break
        yield buf
    proc.stdout.close()
    proc.wait()


def pack_frame(gray: bytes, width: int, height: int, threshold: int) -> bytes:
    """gray is width*height bytes, row-major. Returns packed 1bpp page-format bytes."""
    pages = (height + 7) // 8
    packed = bytearray(pages * width)
    for y in range(height):
        page, bit = y // 8, y % 8
        row_off = y * width
        for x in range(width):
            if gray[row_off + x] > threshold:
                packed[page * width + x] |= (1 << bit)
    return bytes(packed)


def emit_c_array(frames: list, out_path: Path, var_name: str, width: int, height: int):
    frame_bytes = len(frames[0])
    with out_path.open("w") as f:
        f.write("/* Auto-generated by scripts/video_to_frames.py - do not hand-edit. */\n")
        f.write(f"#define {var_name.upper()}_COUNT {len(frames)}u\n")
        f.write(f"#define {var_name.upper()}_WIDTH {width}u\n")
        f.write(f"#define {var_name.upper()}_HEIGHT {height}u\n")
        f.write(f"static const unsigned char {var_name}[{var_name.upper()}_COUNT][{frame_bytes}] = {{\n")
        for frame in frames:
            f.write("  {" + ",".join(str(b) for b in frame) + "},\n")
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("video_file")
    ap.add_argument("output_c_file")
    ap.add_argument("--start", type=float, default=0.0, help="clip start, seconds")
    ap.add_argument("--duration", type=float, default=None, help="clip length, seconds")
    ap.add_argument("--fps", type=int, default=15)
    ap.add_argument("--width", type=int, default=128)
    ap.add_argument("--height", type=int, default=64)
    ap.add_argument("--max-frames", type=int, default=None,
                     help="default: as many as fit in --budget-bytes")
    ap.add_argument("--budget-bytes", type=int, default=84 * 1024,
                     help="frame data size cap when --max-frames isn't given")
    ap.add_argument("--threshold", type=int, default=127, help="0-255 gray cutoff for a lit pixel")
    ap.add_argument("--var-name", default="frames")
    args = ap.parse_args()

    frame_bytes = ((args.height + 7) // 8) * args.width
    max_frames = args.max_frames or (args.budget_bytes // frame_bytes)

    frames = []
    for gray in extract_gray_frames(args.video_file, args.fps, args.width, args.height,
                                     args.start, args.duration):
        if len(frames) >= max_frames:
            break
        frames.append(pack_frame(gray, args.width, args.height, args.threshold))

    if not frames:
        print("ERROR: no frames decoded - check the video path / ffmpeg output", file=sys.stderr)
        sys.exit(1)

    out_path = Path(args.output_c_file)
    emit_c_array(frames, out_path, args.var_name, args.width, args.height)
    total_kb = len(frames) * frame_bytes / 1024
    print(f"OK: {len(frames)} frames ({args.width}x{args.height}) -> {out_path} ({total_kb:.1f} KB)")


if __name__ == "__main__":
    main()
